# SCU35 production pinout, AMD board files v2.0 and HyperRAM reference.
# XDC accepts constraint commands, not Tcl helper procedures or loops.
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVDS} [get_ports {CLK_IN1_D_0_clk_p}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVDS} [get_ports {CLK_IN1_D_0_clk_n}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {ext_reset_in_0}]
set_property -dict {PACKAGE_PIN AC6 IOSTANDARD LVCMOS33} [get_ports {UART_0_rxd}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {UART_0_txd}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {IIC_0_scl_io}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {IIC_0_sda_io}]
# SCU35 schematic A4 sheet 9: dedicated INA700 bus, external 4.7k pull-ups.
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {POWER_IIC_scl_io}]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports {POWER_IIC_sda_io}]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS33} [get_ports {MDIO_0_mdc}]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVCMOS33} [get_ports {MDIO_0_mdio_io}]
set_property -dict {PACKAGE_PIN AE9 IOSTANDARD LVCMOS33} [get_ports {phy_reset_n}]
set_property -dict {PACKAGE_PIN AD7 IOSTANDARD LVCMOS33} [get_ports {MII_0_rxd[0]}]
set_property -dict {PACKAGE_PIN AE5 IOSTANDARD LVCMOS33} [get_ports {MII_0_rxd[1]}]
set_property -dict {PACKAGE_PIN AE6 IOSTANDARD LVCMOS33} [get_ports {MII_0_rxd[2]}]
set_property -dict {PACKAGE_PIN AE7 IOSTANDARD LVCMOS33} [get_ports {MII_0_rxd[3]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports {MII_0_txd[0]}]
set_property -dict {PACKAGE_PIN AC7 IOSTANDARD LVCMOS33} [get_ports {MII_0_txd[1]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports {MII_0_txd[2]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {MII_0_txd[3]}]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD LVCMOS33} [get_ports {MII_0_tx_clk}]
set_property -dict {PACKAGE_PIN AD9 IOSTANDARD LVCMOS33} [get_ports {MII_0_tx_en}]
set_property -dict {PACKAGE_PIN AE11 IOSTANDARD LVCMOS33} [get_ports {MII_0_rx_dv}]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVCMOS33} [get_ports {MII_0_rx_er}]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS33} [get_ports {MII_0_rx_clk}]
set_property -dict {PACKAGE_PIN AE10 IOSTANDARD LVCMOS33} [get_ports {MII_0_col}]
set_property -dict {PACKAGE_PIN AD6 IOSTANDARD LVCMOS33} [get_ports {MII_0_crs}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {MII_0_tx_er[0]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[0]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[1]}]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[2]}]
set_property -dict {PACKAGE_PIN A24 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[3]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[4]}]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[5]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[6]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS18} [get_ports {io_hb_dq_0[7]}]
set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS18} [get_ports {io_hb_rwds_0}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS18} [get_ports {o_hb_cs_n_0}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS18} [get_ports {o_hb_ck_n_0}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS18} [get_ports {o_hb_ck_p_0}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS18} [get_ports {o_hb_reset_n_0}]
set_property DRIVE 8 [get_ports {o_hb_ck_n_0 o_hb_ck_p_0 io_hb_rwds_0}]
set_property DRIVE 12 [get_ports o_hb_cs_n_0]
set_property DRIVE 6 [get_ports {io_hb_dq_0[*]}]
set_property UNAVAILABLE_DURING_CALIBRATION TRUE [get_ports o_hb_cs_n_0]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
